### PR TITLE
enhancement(cli): Adds help info to cli tool

### PR DESCRIPTION
**Pull request by soapdog**
This PR attempts to quickly provide some help information as requested in #21.

Below a screenshot of the help on Windows 10
qbrt-help-win10

A screenshot of the help on Ubuntu
cmder 2017-03-17 18 16 29

### CODE REVIEW

**Comment by mykmelez** [comment]
Thanks, @soapdog, this is tremendously useful! A few notes:

* I'm resolving the TaskCluster build issue over in #23.
* The *path* argument is intended to be specified without the `--path` flag, the way you've documented it in the synopsis as `<path or URL>`. Thus I wouldn't include it as an option in the *Run options* and *Package options* sections. (The module we're using to parse command line flags will allow it to be specified via `--path` as well, but I expect to change that in the future, so I don't want to document that behavior.)
* The `--jsdebugger` and `--wait-for-jsdebugger` flags only apply to *run*, not to *package*. They're also intended to be used by the developers of qbrt itself (i.e. you and me 😉) rather than the developers of apps that use qbrt. (The latter can use `Runtime.openDevTools()` to open a DevTools window for the app, as demonstrated by the *example* and *shell* apps.) I wonder if there's a way to identify them as "internal" options. What would you recommend?

**Comment by soapdog** [comment]
@mykmelez,

Just after sending the PR and shots, I noticed the mistake on the shots and sent a new commit fixing it but forgot to send any shot representing the actual version which looks like:

qbrt zsh 2017-03-18 01-23-00

As for the options, I believe I can add descriptions to them. If that is the case, then I can write that they are optional and be more descriptive of how and when each option should be used. How about that? 😸

**Comment by mykmelez** [comment]
@soapdog Are you still interested in finishing this up? It's almost ready! I think it just needs descriptions for the --jsdebugger and --wait-for-jsdebugger options as well as removal of the --path option.

Here are my recommendations for the descriptions:

For --jsdebugger: Open the runtime toolbox, which is primarily useful for debugging the runtime itself.
And for --wait-for-jsdebugger: Pause the runtime at startup until the runtime toolbox connects.

**Comment by soapdog** [comment]
@mykmelez I am interested, sorry for the delay, will finish them in some hours when I arrive home.

**Comment by soapdog** [comment]
@mykmelez I think it is good now. 😸

**Comment by mykmelez** [comment]
> @mykmelez I think it is good now. 😸

Looks great, thanks @soapdog! I fixed a few style nits (now that master is checking those via eslint) and pushed this to master!

**Pull request merged**
